apiVersion: v1
kind: Service
metadata:
  name: dms-integration
  namespace: uim-platform
  labels:
    app: dms-integration
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: dms-integration
  ports:
  - name: http
    port: 8109
    targetPort: 8109
    protocol: TCP
