apiVersion: v1
kind: Service
metadata:
  name: usage-data
  namespace: uim-platform
  labels:
    app: usage-data
spec:
  type: ClusterIP
  selector:
    app: usage-data
  ports:
  - name: http
    port: 10004
    targetPort: 10004
    protocol: TCP
