apiVersion: v1
kind: Service
metadata:
  name: authorization
  labels:
    app: authorization
spec:
  selector:
    app: authorization
  ports:
  - protocol: TCP
    port: 8117
    targetPort: 8117
  type: ClusterIP
