apiVersion: v1
kind: Service
metadata:
  name: cloud-job-scheduling
  labels:
    app: cloud-job-scheduling
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: cloud-job-scheduling
  ports:
  - name: http
    port: 8096
    targetPort: 8096
    protocol: TCP
