apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: uim-platform
data:
  POSTGRES_HOST: "0.0.0.0"
  POSTGRES_PORT: "8131"
  POSTGRES_PERSISTENCE: "memory"
  POSTGRES_FILE_PATH: "/data"
