apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: uim-platform
  labels:
    app: postgres-service
spec:
  type: ClusterIP
  selector:
    app: postgres-service
  ports:
  - name: http
    port: 8131
    targetPort: 8131
    protocol: TCP
