apiVersion: v1
kind: Service
metadata:
  name: sap-event-mesh
  namespace: uim-platform
  labels:
    app: sap-event-mesh
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: sap-event-mesh
  ports:
  - name: http
    port: 8109
    targetPort: 8109
    protocol: TCP
