apiVersion: v1
kind: Service
metadata:
  name: service-manager
  namespace: uim-platform
  labels:
    app: service-manager
spec:
  type: ClusterIP
  selector:
    app: service-manager
  ports:
  - protocol: TCP
    port: 8113
    targetPort: 8113
