apiVersion: v1
kind: Service
metadata:
  name: cloud-logging
  labels:
    app: cloud-logging
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: cloud-logging
  ports:
    - name: http
      port: 8094
      targetPort: 8094
      protocol: TCP
