apiVersion: v1
kind: Service
metadata:
  name: cloud-solution-lifecycle
  labels:
    app: cloud-solution-lifecycle
spec:
  type: ClusterIP
  selector:
    app: cloud-solution-lifecycle
  ports:
  - name: http
    port: 8097
    targetPort: 8097
    protocol: TCP
