apiVersion: v1
kind: Service
metadata:
  name: integration-delivery
  namespace: uim-platform
  labels:
    app: integration-delivery
spec:
  type: ClusterIP
  selector:
    app: integration-delivery
  ports:
  - name: http
    port: 8120
    targetPort: 8120
    protocol: TCP
