apiVersion: v1
kind: Service
metadata:
  name: build-apps
  namespace: uim-platform
  labels:
    app: build-apps
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: build-apps
  ports:
  - name: http
    port: 8112
    targetPort: 8112
    protocol: TCP
