apiVersion: v1
kind: Service
metadata:
  name: cloud-custom-domain
  labels:
    app: cloud-custom-domain
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: cloud-custom-domain
  ports:
  - name: http
    port: 8101
    targetPort: 8101
    protocol: TCP
