apiVersion: v1
kind: Service
metadata:
  name: responsibility
  namespace: uim-platform
  labels:
    app: responsibility
spec:
  selector:
    app: responsibility
  type: ClusterIP
  ports:
  - name: http
    port: 8118
    targetPort: 8118
    protocol: TCP
