apiVersion: v1
kind: Service
metadata:
  name: AiDocument-ai
  labels:
    app: AiDocument-ai
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: AiDocument-ai
  ports:
  - name: http
    port: 8096
    targetPort: 8096
    protocol: TCP
