apiVersion: v1
kind: ConfigMap
metadata:
  name: architecture-config
  namespace: uim-platform
  labels:
    app: architecture
    component: building-blocks
data:
  ARCHITECTURE_HOST: "0.0.0.0"
  ARCHITECTURE_PORT: "8122"
