apiVersion: v1
kind: Service
metadata:
  name: health-fhir
  labels:
    app: health-fhir
    layer: platform
spec:
  type: ClusterIP
  selector:
    app: health-fhir
  ports:
  - name: http
    port: 8097
    targetPort: 8097
    protocol: TCP
