apiVersion: v1
kind: Service
metadata:
  name: uim-print-platform-service
  namespace: uim-platform
  labels:
    app: print
    component: uim-platform
spec:
  type: ClusterIP
  selector:
    app: print
  ports:
  - name: http
    port: 8120
    targetPort: 8120
    protocol: TCP
