apiVersion: v1
kind: Service
metadata:
  name: cloud-snowflake
  labels:
    app: cloud-snowflake
spec:
  type: ClusterIP
  selector:
    app: cloud-snowflake
  ports:
  - protocol: TCP
    port: 8100
    targetPort: 8100
