apiVersion: v1
kind: Service
metadata:
  name: uim-private-link-platform-service
  namespace: uim-platform
  labels:
    app: uim-private-link-platform-service
    component: private-link
spec:
  type: ClusterIP
  selector:
    app: uim-private-link-platform-service
  ports:
  - name: http
    port: 8087
    targetPort: 8087
    protocol: TCP
