apiVersion: v1
kind: Service
metadata:
  name: event-mesh
  namespace: uim-platform
  labels:
    app: event-mesh
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: event-mesh
  ports:
  - name: http
    port: 8108
    targetPort: 8108
    protocol: TCP
