apiVersion: v1
kind: Service
metadata:
  name: cloud-hana-spatial
  labels:
    app: cloud-hana-spatial
    component: spatial-services
spec:
  type: ClusterIP
  selector:
    app: cloud-hana-spatial
  ports:
  - name: http
    port: 8098
    targetPort: 8098
    protocol: TCP
