apiVersion: v1
kind: Service
metadata:
  name: masterdata-governance
  namespace: uim-platform
  labels:
    app: masterdata-governance
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: masterdata-governance
  ports:
  - name: http
    port: 8108
    targetPort: 8108
    protocol: TCP
