apiVersion: v1
kind: Service
metadata:
  name: customer-identity
  namespace: uim-platform
  labels:
    app: customer-identity
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: customer-identity
  ports:
  - name: http
    port: 8119
    targetPort: 8119
    protocol: TCP
