apiVersion: v1
kind: ConfigMap
metadata:
  name: field-service-config
  namespace: uim-platform
  labels:
    app: field-service
    part-of: uim-platform
data:
  FIELD_SERVICE_HOST: "0.0.0.0"
  FIELD_SERVICE_PORT: "8107"
