apiVersion: v1
kind: Service
metadata:
  name: application-events-service
  namespace: uim-platform
spec:
  selector:
    app: application-events-service
  ports:
  - protocol: TCP
    port: 8132
    targetPort: 8132
  type: ClusterIP
