apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-suite-config
  labels:
    app: integration-suite
    part-of: uim-platform
data:
  INTEGRATION_SUITE_HOST: "0.0.0.0"
  INTEGRATION_SUITE_PORT: "8096"
