apiVersion: v1
kind: Service
metadata:
  name: integration-suite
  labels:
    app: integration-suite
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: integration-suite
  ports:
  - name: http
    port: 8096
    targetPort: 8096
    protocol: TCP
