apiVersion: v1
kind: Service
metadata:
  name: cloud-hana
  labels:
    app: cloud-hana
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: cloud-hana
  ports:
  - name: http
    port: 8097
    targetPort: 8097
    protocol: TCP
