apiVersion: v1
kind: Service
metadata:
  name: cloud-feature-flags
  labels:
    app: cloud-feature-flags
    tier: platform-service
spec:
  selector:
    app: cloud-feature-flags
  ports:
  - name: http
    port: 8097
    targetPort: 8097
    protocol: TCP
  type: ClusterIP
