apiVersion: v1
kind: ConfigMap
metadata:
  name: market-refinitiv-config
  labels:
    app: market-refinitiv
    tier: platform-service
data:
  MARKET_RATES_HOST: "0.0.0.0"
  MARKET_RATES_PORT: "8097"
