apiVersion: v1
kind: Service
metadata:
  name: market-refinitiv
  labels:
    app: market-refinitiv
    tier: platform-service
spec:
  type: ClusterIP
  selector:
    app: market-refinitiv
  ports:
  - name: http
    port: 8097
    targetPort: 8097
    protocol: TCP
