apiVersion: v1
kind: Service
metadata:
  name: oauth
  namespace: uim-platform
  labels:
    app: oauth
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: oauth
  ports:
  - name: http
    port: 8114
    targetPort: 8114
    protocol: TCP
