apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization-trust-config
  labels:
    app: authorization-trust
    part-of: uim-platform
data:
  AUTHORIZATION_TRUST_HOST: "0.0.0.0"
  AUTHORIZATION_TRUST_PORT: "8116"
