apiVersion: v1
kind: Service
metadata:
  name: authorization-trust
  labels:
    app: authorization-trust
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: authorization-trust
  ports:
  - name: http
    port: 8116
    targetPort: 8116
    protocol: TCP
