apiVersion: v1
kind: Service
metadata:
  name: automation-pilot
  namespace: uim-platform
  labels:
    app: automation-pilot
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: automation-pilot
  ports:
  - name: http
    port: 8110
    targetPort: 8110
    protocol: TCP
