apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: uim-platform
  labels:
    app: redis-service
spec:
  type: ClusterIP
  selector:
    app: redis-service
  ports:
  - name: http
    port: 8130
    targetPort: 8130
    protocol: TCP
