apiVersion: v1
kind: Service
metadata:
  name: data-retention
  namespace: uim-platform
  labels:
    app: data-retention
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: data-retention
  ports:
  - name: http
    port: 8112
    targetPort: 8112
    protocol: TCP
