apiVersion: v1
kind: Service
metadata:
  name: application-studio
  namespace: uim-platform
  labels:
    app: application-studio
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: application-studio
  ports:
  - name: http
    port: 8111
    targetPort: 8111
    protocol: TCP
