name: Cloud Portal Service CI

on:
  push:
    paths:
      - 'cloud-portal/**'
  pull_request:
    paths:
      - 'cloud-portal/**'

jobs:
  build:
    name: Build Cloud Portal Service
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [dmd-latest, ldc-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.compiler }}

      - name: Build
        working-directory: cloud-portal
        run: |
          dub upgrade
          dub build

      - name: Test
        working-directory: cloud-portal
        run: dub test || true
